"""KG task 6: add a `source` field to every row of every knowledge table (text edits that keep comments) and
count rows per source category. Categories: RadLex ID; Chest ImaGenome; CheXpert label hierarchy;
Fleischner glossary; RadReport template; author-curated, needs review. Idempotent: rows that already have a
source are left as they are. Run after build_anatomy.py / build_radlex_map.py.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd  # noqa: E402
import yaml  # noqa: E402

from nesy.runlog import Run  # noqa: E402

KG = Path(__file__).resolve().parents[1] / "kg"
CHEX = "CheXpert label hierarchy (Irvin et al. 2019)"
CUR = "author-curated, needs review"
RR = "RadReport template 'Rad Chest 2 Views'"
FINDING_SRC = {f: f"{CHEX}: label" for f in ["lung_opacity", "atelectasis", "consolidation", "pneumonia", "edema", "lung_lesion",
                                            "enlarged_cardiomediastinum", "cardiomegaly", "pleural_effusion", "pleural_other",
                                            "pneumothorax", "fracture", "support_devices"]}
FINDING_SRC["any_abnormality"] = f"{CUR} (root node; complement of CheXpert 'No Finding')"
ISA_SRC = {f"isa_00{i}": CHEX for i in range(1, 7)}
PN_SRC = {"pn_001": f"{RR}: 'No pneumothorax.'", "pn_002": f"{RR}: pleural effusion pick-list / 'No pleural abnormalities'",
          "pn_003": f"{CUR} (template says 'The lungs are clear.')", "pn_004": f"{RR}: 'The heart is normal in size.'",
          "pn_005": f"{RR}: 'no evidence of associated pulmonary edema' (the condition is {CUR})"}


def q(s):
    return '"' + s.replace('"', "'") + '"'


def add_flow(text, section_ids, src_of):
    def rep(m):
        row = m.group(0)
        if "source:" in row:
            return row
        rid = re.search(r"id: (\w+)", row).group(1)
        return row[:-2] + f", source: {q(src_of(rid))}}}\n"
    return re.sub(r"  - \{id: (" + section_ids + r")[^\n]*\}\n", rep, text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", default=None)
    a = ap.parse_args()
    with Run("add-sources", vars(a), a.run_dir) as run:
        # findings.yaml
        p = KG / "findings.yaml"
        s = p.read_text()
        for f, src in FINDING_SRC.items():
            s = re.sub(rf"(  - id: {f}\n)(?!    source:)", rf"\1    source: {q(src)}\n", s)
        s = add_flow(s, r"isa_\d+", lambda i: ISA_SRC.get(i, f"{CUR} (root edge)"))
        s = add_flow(s, r"aw_\d+", lambda i: f"{CUR} (clinical association)")
        s = add_flow(s, r"pn_\d+", lambda i: PN_SRC[i])
        s = re.sub(r"(  id: n1_critical_absent\n)(?!  source:)", rf"\1  source: {q(CUR + ' (inactive)')}\n", s)
        p.write_text(s)
        # imagenome_map.yaml and external maps: block entries at 2-space indent under map: / findings:
        for fn, src in (("imagenome_map.yaml", f"Chest ImaGenome labels (semantics/attribute_relations_v1.txt); mapping {CUR}"),
                        ("external_maps/vindr_to_findings.yaml", f"VinDr-CXR label list; mapping {CUR}"),
                        ("external_maps/padchest_gr_to_findings.yaml", f"PadChest-GR label list; mapping {CUR}")):
            p = KG / fn
            s = p.read_text()
            s = re.sub(r"(\n  [a-z_]+:\n)(?!    source:)", lambda m: m.group(1) + f"    source: {q(src)}\n", s)
            s = re.sub(r"^(  [a-z_]+: \{[^\n]*?)\}$", lambda m: m.group(0) if "source:" in m.group(0) else m.group(1) + f", source: {q(src)}}}", s, flags=re.M)
            s = re.sub(r"(\nno_finding: \{[^\n]*?)\}\n", lambda m: m.group(0) if "source:" in m.group(0) else m.group(1) + f", source: {q(src)}}}\n", s)
            p.write_text(s)
        # anatomy.yaml (generated by build_anatomy.py; sources added here)
        rl = {e["key"]: e for e in yaml.safe_load((KG / "radlex_map.yaml").read_text())["entries"] if e["kind"] == "anatomy"}
        p = KG / "anatomy.yaml"
        s = p.read_text()
        if "sources added by v2/scripts/add_sources.py" not in s:
            s = s.replace("# GENERATED by v2/scripts/build_anatomy.py; edit there, not here.",
                          "# GENERATED by v2/scripts/build_anatomy.py; edit there, not here. `source` fields: sources added by v2/scripts/add_sources.py (rerun after a rebuild).", 1)

        def anat(m):
            nid = m.group(1)
            e = rl.get(nid)
            src = e["source"] if e and e.get("radlex_id") else f"Chest ImaGenome region name; {CUR}"
            if e and e["match"] == "approximate":
                src += f" (approximate: {e['note']})"
            return m.group(0) + f"  source: {q(src)}\n"
        s = re.sub(r"- id: (\w+)\n(?!  source:)", anat, s)
        p.write_text(s)

        # ---- count rows per category across all tables
        def cat(src):
            s = src.lower()
            if s.startswith("no "):
                return "no external source (no matching term)"
            for key, name in (("radlex", "RadLex ID"), ("imagenome", "Chest ImaGenome"), ("chexpert", "CheXpert label hierarchy"),
                              ("fleischner", "Fleischner glossary"), ("radreport", "RadReport template")):
                if key in s and not s.startswith("author-curated"):
                    return name
            return "author-curated, needs review"
        rows = []
        fd = yaml.safe_load((KG / "findings.yaml").read_text())
        for f in fd["findings"]:
            rows.append(("findings", f["id"], f["source"]))
            rows.append(("finding definitions (glossary)", f["id"], f["glossary"]["source"]))
        for sec in ("is_a", "may_occur_in", "associated_with", "pertinent_negatives"):
            rows += [(sec, e["id"], e["source"]) for e in fd[sec]]
        rows.append(("normal_call", fd["normal_call"]["id"], fd["normal_call"]["source"]))
        for n in yaml.safe_load((KG / "anatomy.yaml").read_text())["nodes"]:
            rows.append(("anatomy", n["id"], n["source"]))
        for e in yaml.safe_load((KG / "radlex_map.yaml").read_text())["entries"]:
            rows.append(("radlex_map", f"{e['kind']}:{e['key']}", e["source"]))
        for e in yaml.safe_load((KG / "devices.yaml").read_text())["device_types"]:
            rows.append(("devices", e["id"], e["source"]))
        im = yaml.safe_load((KG / "imagenome_map.yaml").read_text())["map"]
        rows += [("imagenome_map", k, v["source"]) for k, v in im.items()]
        for fn in ("vindr_to_findings.yaml", "padchest_gr_to_findings.yaml"):
            d = yaml.safe_load((KG / "external_maps" / fn).read_text())
            rows += [(fn, k, v["source"]) for k, v in d["findings"].items()]
            if "no_finding" in d:
                rows.append((fn, "no_finding", d["no_finding"]["source"]))
        df = pd.DataFrame(rows, columns=["table", "row", "source"])
        df["category"] = df.source.map(cat)
        df.to_csv(run.dir / "sources.csv", index=False)
        tab = df.groupby(["table", "category"]).size().unstack(fill_value=0)
        tab.loc["TOTAL"] = tab.sum()
        tab.to_csv(run.dir / "source_counts.csv")
        pd.set_option("display.width", 220)
        run.log(f"rows {len(df)}; missing source {int(df.source.isna().sum())}\n" + tab.to_string())


if __name__ == "__main__":
    main()
